
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  db:
    image: mysql:8.0
    container_name: wordwench-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordwench
    ports:
      - "3306:3306"
